version: '3'
services:
  kafka1:
    image: nijanthan/confluentkafkakraft:7.2.1-3.2.0
    container_name: Confluentkafka1
    ports:
        - "9093:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://Confluentkafka1:9092,CONTROLLER://Confluentkafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Confluentkafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@Confluentkafka1:9093,2@Confluentkafka2:9093,3@Confluentkafka3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'

  kafka2:
    image: nijanthan/confluentkafkakraft:7.2.1-3.2.0
    container_name: Confluentkafka2
    ports:
        - "9094:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://Confluentkafka2:9092,CONTROLLER://Confluentkafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Confluentkafka2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@Confluentkafka1:9093,2@Confluentkafka2:9093,3@Confluentkafka3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'

  kafka3:
    image: nijanthan/confluentkafkakraft:7.2.1-3.2.0
    container_name: Confluentkafka3
    ports:
        - "9095:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://Confluentkafka3:9092,CONTROLLER://Confluentkafka3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Confluentkafka3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@Confluentkafka1:9093,2@Confluentkafka2:9093,3@Confluentkafka3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'