version: "3.8"
services:
  kafka1:
    container_name: Apachekafka1
    image: nijanthan/apachekafkakraft
    build: 
      context: .
    ports:
        - "9092:9092"
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: Apachekafka2
    image: nijanthan/apachekafkakraft
    build: 
      context: .
    ports:
        - "9292:9092"
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: Apachekafka3
    image: nijanthan/apachekafkakraft
    build: 
      context: .
    ports:
        - "9392:9092"
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/